### PR TITLE
Devstack fix

### PR DESCRIPTION
**Pull request by dane-johnson**
Fixes bug in devstack that would cause it to fail if the redis container already exists

### CODE REVIEW

**Comment by dane-johnson** [comment]
Wouldn't this fail if it existed but wasn't running?

**Comment by thebho** [comment]
It just logs the error and the variable stays false

**Comment by dane-johnson** [comment]
@thebho Not gonna lie, having a pretty hard time with this.

**Comment by thebho** [comment]
It's a little different because you aren't using a compose file.  We can chat about it tomorrow at MT

**Comment by dane-johnson** [comment]
Can now confirm this does indeed work

**Pull request merged**
