### PR TITLE
Removed Golang parser

### LINKED ISSUE #60: Disable inactive parsers
I like that you can see the "Go" language selector, but we should disable that selection until we have that functionality

### PR DESCRIPTION
**Pull request by solkaz**
Fixes #60

### CODE REVIEW

**Comment by solkaz** [comment]
Do we want to also disable the LanguageSelector? Since they can only select one language

**Comment by dane-johnson** [comment]
I say leave it. If nothing else it let's the user know that this is an ongoing project and there will be more languages in the future.

**Comment by thebho** [comment]
Let's disable it.  And I'm wondering if it should be Java instead of Go, because that is next on the list

**Comment by solkaz** [comment]
@thebho `LanguageSelector` is now disabled

**Pull request merged**
