### PR TITLE
Editor fix

### PR DESCRIPTION
**Pull request by solkaz**
## Description
Few more UI changes

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by thebho** [comment]
Can you be more specific and add photos?

**Comment by solkaz** [comment]
screen shot 2017-05-12 at 9 17 07 am
screen shot 2017-05-12 at 9 17 14 am

**Comment by solkaz** [comment]
It adds overflow to the AppBody so that it doesn't spill over the Contact Us section

**Comment by thebho** [comment]
Got it

**Pull request merged**
