### PR TITLE
Issue115

### LINKED ISSUE #115: Allow users to login to their github account

### PR DESCRIPTION
**Pull request by dane-johnson**
closes #115 
~WIP, still needs~ **Ready for merge**
- [x] Better looking login button
- [x] Better loading screen while awaiting github
- [x] Redirect to calling page instead of back to home
- [x] Show an error if login fails
- [x] Display the user's GitHub [avatar](http://www.material-ui.com/#/components/avatar)
- [x] Snapshots of UI elements

## Before Logged In
screen shot 2017-03-10 at 9 41 16 am

## While Logging In (Loading)
screen shot 2017-03-10 at 8 58 47 am

## After Logged In
screen shot 2017-03-10 at 9 41 33 am

## On Failure to Log In
screen shot 2017-03-10 at 3 55 40 pm

### CODE REVIEW

**Comment by thebho** [comment]
Test

**Comment by thebho** [comment]
Closing

**Comment by dane-johnson** [comment]
Not sure about that all red backdrop. Kinda painful to look at.

**Comment by Hopding** [comment]
Would you prefer the dialog be red, and the backdrop be white?

**Comment by dane-johnson** [comment]
Sounds better

**Comment by Hopding** [comment]
I've updated the styling of `<Alert isError={true}/>` components. I think in the long term, it will be better to display a snackbar to the user instead of an `<Alert />`. But implementing it will be significantly easier once we have merged the Redux branch. So, all else withstanding, I would like to merge this now, and make a separate story to use a snackbar to render login errors.

**Comment by Hopding** [comment]
The styling on `<Alert />` components has been removed:
screen shot 2017-03-10 at 3 55 40 pm

**Pull request merged**
