### PR TITLE
Moves annotation navigation buttons to top of view

### LINKED ISSUE #432: Relocate next/prev buttons
## Expected Behavior

It should be possible to move through the next/prev annotations in a snippet, regardless of an annotation's length, without having to move my cursor up/down.

## Current Behavior

If I am viewing annotations of different lengths, then the buttons will shift up and down depending on the annotation's size, thereby forcing me to move my cursor to use the next/prev buttons.

## Screenshots
Notice the differing locations of the next/prev buttons in the screenshots below:

### Annotation with shorter height
screen shot 2017-04-25 at 3 59 15 pm

### Annotation with greater height
screen shot 2017-04-25 at 3 59 30 pm

### PR DESCRIPTION
**Pull request by dane-johnson**
## Description

Pure UI change, see screenshot

## Motivation and Context

Closes #432
## Checklist:

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

## Screenshots (if appropriate):
screen shot 2017-05-03 at 9 41 06 am

### CODE REVIEW

**Comment by thebho** [comment]
I'm not sure about separating the Annotation from it's snippet preview.  Maybe permanent `<>` on a toolbar is the better answer

**Comment by dane-johnson** [comment]
Like the big one?

**Comment by thebho** [comment]
Why isn't this offering me to update from master?

**Comment by thebho** [comment]
This is going to have to be reopened after a rebase from master

**Pull request closed without merging**
