### PR TITLE
AnnotationCreator closes when saving

### LINKED ISSUE #97: After saving an annotation, the save and cancel buttons should go away and become close.
This is a regression.

### PR DESCRIPTION
**Pull request by solkaz**
Fixes #97

### CODE REVIEW

**Comment by thebho** [comment]
Does this close the whole panel, or just replace the Save/Cancel buttons?  The story is to remove the buttons

**Comment by solkaz** [comment]
I thought I simply had to reimplement the behavior from before, so it closes the whole panel

**Comment by solkaz** [comment]
I'm about to eat lunch but afterwards I should have this fixed

**Comment by dane-johnson** [comment]
I think it should change to the display view

**Comment by dane-johnson** [comment]
So basically
screen shot 2017-03-02 at 11 47 14 am
Then on save
screen shot 2017-03-02 at 11 47 25 am

**Comment by solkaz** [comment]
That's the point of the story. I thought we were just reverting to previous behaior

**Comment by thebho** [comment]
Staying in Edit Mode is the regression.  I was assuming in the previous story that "saving" would leave the annotation open but convert to View Mode.

**Comment by solkaz** [comment]
@thebho @dane-johnson fixed

**Pull request merged**
