### PR TITLE
Add buttons to view previous/next annotations

### LINKED ISSUE #228: Add Next/Prev Buttons to Annotations Viewer
When viewing an annotation, it should be possible to choose to view the next or previous annotations. This should also support use of the arrow keys.

### PR DESCRIPTION
**Pull request by solkaz**
## Description
This PR adds two buttons in the `AnnotationDisplay` component to view the previous/next annotation. If there isn't before/after it, the buttons will be disabled.

## Motivation and Context
Fixes #228 

## Checklist:

- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by thebho** [comment]
Can you add a screenshot or video?

**Comment by dane-johnson** [comment]
Screenshots?

**Comment by solkaz** [comment]
In the slack channel or you can checkout the branch to view it

**Comment by dane-johnson** [comment]
screen shot 2017-04-12 at 11 23 27 am

**Pull request merged**
