### PR TITLE
Logout users with invalid tokens

### LINKED ISSUE #465: Logout users with expired tokens
## Expected Behavior

Users should be asked to log back in if they have expired/invalid tokens.

## Current Behavior

Currently, if a user performs an operation that results in a call to the API, and the API responds with a `400` due to an invalid auth token, the user is not notified of _why_ the operation failed, but only the fact of it. Instead, they should be prompted to log back into the app in order to obtain a valid auth token.

## Possible Solution

Create a redux action that when invoked, logs the user out of the app, and displays a modal requesting that they log back in. Parse all responses from API requests that can fail due to invalid tokens, and dispatch that action when they fail because of an invalid token.

### PR DESCRIPTION
**Pull request by solkaz**
## Description
- When a user attempts to access their information with an invalid Github token, the application will clear their credentials and reset the application. This will occur early in the application life cycle, specifically in `<CodesplainAppBar />`'s `componentDidMount` method.
- Abstracts much of the promise logic away from the component, and instead lets the thunks handle them.

- This PR relies on [this PR](https://github.com/maryvilledev/codesplain-lambdas/pull/117) being merged in order to work correctly

## Motivation and Context
Fix #465 

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari

### CODE REVIEW

**Comment by thebho** [comment]
Why did you refactor all the gists stuff?

**Comment by solkaz** [comment]
@thebho part of refactoring the CodesplainAppBar, so that most of the logic is abstracted away.

**Comment by solkaz** [comment]
This "works", but I cannot figure out a way to test this. Merge at your own discretion

**Comment by thebho** [comment]
Do you mean you don't have a way to write unit tests, or you have never actually seen the code work?

**Comment by solkaz** [comment]
I don't have a way to write unit tests. I can verify that this works in all browsers, though

**Pull request merged**
